export const SAMPLE_PROJECT_NAME = "Sample project (synthetic)";
export const SAMPLE_ASSET_FILENAME = "sample-origin-record.png";
export const SAMPLE_ASSET_MIME = "image/png";
export const SAMPLE_SOURCE_NOTES =
  "Synthetic sample generated by OriginLedger for onboarding. This is not a real product photograph or origin record.";
