import { expect, test, type Page } from "@playwright/test";

const PNG = Buffer.from(
  "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a4944415478da63000000020001005e0dc8d20000000049454e44ae426082",
  "hex",
);

async function signUp(page: Page, email: string) {
  await page.goto("/sign-up");
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("correct1");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page.getByRole("heading", { name: "Workspace" })).toBeVisible({
    timeout: 30_000,
  });
}

async function createReadyAsset(page: Page) {
  await page.getByLabel("Organization name").fill("Declaration Org");
  await page.getByRole("button", { name: "Create organization" }).click();
  await expect(page.getByLabel("Project name")).toBeVisible({
    timeout: 15_000,
  });
  await page.getByLabel("Project name").fill("Declaration project");
  await page.getByRole("button", { name: "Create project" }).click();
  await page.getByRole("link", { name: "Declaration project" }).click();
  await page.locator('input[name="file"]').setInputFiles({
    name: "lot.png",
    mimeType: "image/png",
    buffer: PNG,
  });
  await page.getByRole("button", { name: "Upload file" }).click();
  await expect(page.getByText("Status: ready")).toBeVisible({
    timeout: 30_000,
  });
}

async function fillRemainingWizard(page: Page) {
  await page.getByRole("button", { name: "1. Creation mode" }).click();
  await page.getByLabel("Generated by AI").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByRole("textbox", { name: "Provider" }).fill("Northwind");
  await page
    .getByRole("textbox", { name: "Model", exact: true })
    .fill("OriginDraw");
  await page.getByRole("textbox", { name: "Model version" }).fill("3");
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Prompt summary").fill("Studio photograph of a crate.");
  await expect(
    page.getByLabel("Store the raw prompt (optional)"),
  ).not.toBeChecked();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Substantial human edits").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("United States").check();
  await page.getByLabel("Product documentation").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Stylized").check();
  await page.getByLabel("No public-interest information").check();
  await page.getByLabel("Internally reviewed").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await expect(page.getByText("Prompt summary")).toBeVisible();
  await page.getByRole("button", { name: "Submit for human review" }).click();
}

test.describe("provenance declarations", () => {
  test("saves a draft, resumes, submits, and records human review", async ({
    page,
  }) => {
    const email = `declare-${Date.now()}@example.com`;
    await signUp(page, email);
    await createReadyAsset(page);
    await page.getByRole("link", { name: "Provenance declaration" }).click();
    await expect(
      page.getByRole("heading", { name: "Provenance declaration" }),
    ).toBeVisible();

    await page.getByLabel("Generated by AI").check();
    await page.getByRole("button", { name: "Continue" }).click();
    await page.getByRole("textbox", { name: "Provider" }).fill("Northwind");
    await page.getByRole("button", { name: "Save draft" }).click();
    await expect(page.getByText("Draft saved.")).toBeVisible();
    await page.reload();
    await page.getByRole("button", { name: "2. Provider and model" }).click();
    await expect(page.getByRole("textbox", { name: "Provider" })).toHaveValue(
      "Northwind",
    );
    await page.getByRole("button", { name: "1. Creation mode" }).click();
    await expect(page.getByLabel("Generated by AI")).toBeChecked();

    await fillRemainingWizard(page);
    await expect(page.getByText("Pending human review")).toBeVisible({
      timeout: 15_000,
    });
    await expect(
      page.getByText(
        "A human reviewer must make the final disclosure decision.",
      ),
    ).toBeVisible();
    await expect(
      page.getByText("not a final compliance decision"),
    ).toBeVisible();
    await expect(page.getByText("disclosure-rules.v1")).toBeVisible();

    await page.getByRole("button", { name: "Record human review" }).click();
    await expect(page.getByText("Reviewed declaration")).toBeVisible({
      timeout: 15_000,
    });

    await page
      .getByRole("button", { name: "Create a new version to edit" })
      .click();
    await expect(page.getByText("Draft declaration")).toBeVisible({
      timeout: 15_000,
    });
    await expect(page.getByText("version 2")).toBeVisible();
  });

  test("does not expose another tenant's declaration", async ({
    page,
    browser,
  }) => {
    await signUp(page, `declare-a-${Date.now()}@example.com`);
    await createReadyAsset(page);
    await page.getByRole("link", { name: "Provenance declaration" }).click();
    const declarationUrl = page.url();

    const outsiderContext = await browser.newContext();
    const outsider = await outsiderContext.newPage();
    await signUp(outsider, `declare-b-${Date.now()}@example.com`);
    await outsider.goto(declarationUrl);
    await expect(
      outsider.getByRole("heading", { name: "This page could not be found." }),
    ).toBeVisible();
    await outsiderContext.close();
  });
});
