import { expect, test, type Page } from "@playwright/test";
import { expectStatus } from "./helpers/status";

const PNG = Buffer.from(
  "89504e470d0a1a0a0000000d49484452000000010000000108060000001f15c4890000000a4944415478da63000000020001005e0dc8d20000000049454e44ae426082",
  "hex",
);

async function signUp(page: Page, email: string) {
  await page.goto("/sign-up");
  await page.getByLabel("Email").fill(email);
  await page.getByLabel("Password").fill("correct1");
  await page.getByRole("button", { name: "Create account" }).click();
  await expect(page.getByRole("heading", { name: "Workspace" })).toBeVisible({
    timeout: 30_000,
  });
}

async function createReadyAsset(page: Page) {
  await page.getByLabel("Organization name").fill("Declaration Org");
  await page.getByRole("button", { name: "Create organization" }).click();
  await expect(page.getByLabel("Project name")).toBeVisible({
    timeout: 15_000,
  });
  await page.getByLabel("Project name").fill("Declaration project");
  await page.getByRole("button", { name: "Create project" }).click();
  await page
    .getByRole("link", { name: "Declaration project", exact: true })
    .click();
  await page.locator('input[name="file"]').setInputFiles({
    name: "lot.png",
    mimeType: "image/png",
    buffer: PNG,
  });
  await page.getByRole("button", { name: "Upload file" }).click();
  await expectStatus(page, "ready");
}

async function fillWizardWithRawPrompt(page: Page) {
  await page.getByRole("button", { name: "1. Creation mode" }).click();
  await page.getByLabel("Generated by AI").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByRole("textbox", { name: "Provider" }).fill("Northwind");
  await page
    .getByRole("textbox", { name: "Model", exact: true })
    .fill("OriginDraw");
  await page.getByRole("textbox", { name: "Model version" }).fill("3");
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Prompt summary").fill("Studio photograph of a crate.");
  await page.getByLabel("Store the raw prompt (optional)").check();
  await page
    .getByRole("textbox", { name: "Raw prompt" })
    .fill("unique-raw-prompt-token-xyz");
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Substantial human edits").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("United States").check();
  await page.getByLabel("Product documentation").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByLabel("Stylized").check();
  await page.getByLabel("No public-interest information").check();
  await page.getByLabel("Internally reviewed").check();
  await page.getByRole("button", { name: "Continue" }).click();
  await page.getByRole("button", { name: "Submit for human review" }).click();
}

async function downloadFirstPacketText(page: Page) {
  const [download] = await Promise.all([
    page.waitForEvent("download"),
    page.getByRole("link", { name: "Download packet" }).first().click(),
  ]);
  const path = await download.path();
  if (!path) {
    throw new Error("download path missing");
  }
  const fs = await import("node:fs/promises");
  return fs.readFile(path, "utf8");
}

test.describe("evidence packets and share links", () => {
  test("generates JSON and PDF packets, defaults raw prompts off, and shares securely", async ({
    page,
    browser,
    request,
  }) => {
    await signUp(page, `packet-${Date.now()}@example.com`);
    await createReadyAsset(page);
    await page.getByRole("link", { name: "Provenance declaration" }).click();
    await fillWizardWithRawPrompt(page);
    await expect(page.getByText("Pending human review")).toBeVisible({
      timeout: 15_000,
    });
    await page.getByRole("button", { name: "Record human review" }).click();
    await expect(page.getByText("Reviewed declaration")).toBeVisible({
      timeout: 15_000,
    });

    await page.getByRole("link", { name: "Back to file" }).click();
    await page.getByRole("link", { name: "Evidence packets" }).click();
    await expect(
      page.getByRole("heading", { name: "Evidence packets" }),
    ).toBeVisible();
    await expect(
      page.getByLabel(/Include the raw prompt in this export/),
    ).not.toBeChecked();

    await page
      .getByRole("button", { name: "Generate evidence packet" })
      .click();
    await expect(page.getByText("Evidence packet generated.")).toBeVisible({
      timeout: 15_000,
    });
    await expect(page.getByText("raw prompt omitted")).toBeVisible();

    const defaultJson = await downloadFirstPacketText(page);
    expect(defaultJson).toContain("evidence-packet.v1");
    expect(defaultJson.includes("unique-raw-prompt-token-xyz")).toBe(false);
    expect(defaultJson).toContain("not a government, legal, authenticity");
    expect(defaultJson).toContain("disclosure-rules.v1");

    await page.getByLabel(/Include the raw prompt in this export/).check();
    await page
      .getByRole("button", { name: "Generate evidence packet" })
      .click();
    await expect(page.getByText("raw prompt included")).toBeVisible({
      timeout: 15_000,
    });
    const includedJson = await downloadFirstPacketText(page);
    expect(includedJson).toContain("unique-raw-prompt-token-xyz");

    await page.locator('select[name="format"]').selectOption("pdf");
    await page.getByLabel(/Include the raw prompt in this export/).uncheck();
    await page
      .getByRole("button", { name: "Generate evidence packet" })
      .click();
    await expect(page.getByText("PDF · evidence-packet.v1")).toBeVisible({
      timeout: 15_000,
    });

    await page
      .getByRole("button", { name: "Create share link" })
      .first()
      .click();
    await expect(
      page.getByText("Copy this link now. It will not be shown again."),
    ).toBeVisible();
    const shareUrl = await page.locator("code").innerText();
    expect(shareUrl).toContain("/share/");

    const sharePage = await browser.newPage();
    const response = await sharePage.goto(shareUrl);
    expect(response?.headers()["x-robots-tag"]).toMatch(/noindex/);
    expect(response?.headers()["cache-control"]).toMatch(/no-store/);
    expect(response?.headers()["referrer-policy"]).toBe("no-referrer");
    await expect(sharePage).toHaveTitle(/Shared document/);
    await expect(sharePage.getByText("Workspace")).toHaveCount(0);
    await expect(sharePage.getByText("Declaration Org")).toHaveCount(0);
    await expect(
      sharePage.getByText("unique-raw-prompt-token-xyz"),
    ).toHaveCount(0);
    await expect(
      sharePage.getByRole("link", { name: "Download packet" }),
    ).toBeVisible();

    const [sharedDownload] = await Promise.all([
      sharePage.waitForEvent("download"),
      sharePage.getByRole("link", { name: "Download packet" }).click(),
    ]);
    expect(sharedDownload.suggestedFilename()).toMatch(/^packet\.(json|pdf)$/);

    await page.getByRole("button", { name: "Revoke" }).first().click();
    await expect(page.getByText("Share link revoked.")).toBeVisible();
    await sharePage.goto(shareUrl);
    await expect(
      sharePage.getByText("This shared document is unavailable."),
    ).toBeVisible();
    await expect(sharePage.getByText("Declaration Org")).toHaveCount(0);
    await expect(sharePage).toHaveTitle(/Shared document/);

    const invalid = await sharePage.goto(`${shareUrl}not-a-valid-token`);
    expect(invalid?.headers()["x-robots-tag"]).toMatch(/noindex/);
    await expect(
      sharePage.getByText("This shared document is unavailable."),
    ).toBeVisible();
    await sharePage.close();

    const supabaseUrl =
      process.env.NEXT_PUBLIC_SUPABASE_URL ?? "http://127.0.0.1:54321";
    const storage = await request.get(
      `${supabaseUrl}/storage/v1/object/public/evidence-packets/exports/does-not-exist`,
    );
    expect(storage.ok()).toBeFalsy();
  });

  test("does not expose another tenant's exports", async ({
    page,
    browser,
  }) => {
    await signUp(page, `packet-a-${Date.now()}@example.com`);
    await createReadyAsset(page);
    await page.getByRole("link", { name: "Evidence packets" }).click();
    const exportUrl = page.url();

    const outsiderContext = await browser.newContext();
    const outsider = await outsiderContext.newPage();
    await signUp(outsider, `packet-b-${Date.now()}@example.com`);
    await outsider.goto(exportUrl);
    await expect(
      outsider.getByRole("heading", { name: "Page not found" }),
    ).toBeVisible();
    await outsiderContext.close();
  });
});
