import {
  CONTENT_CATEGORIES,
  CREATION_MODES,
  DISTRIBUTION_REGIONS,
  EDITORIAL_REVIEW_STATUSES,
  HUMAN_EDITS,
  PUBLIC_INTEREST_STATUSES,
  REALISTIC_DEPICTIONS,
} from "@/server/declarations/schema";

export const CREATION_MODE_LABELS: Record<
  (typeof CREATION_MODES)[number],
  string
> = {
  human_created: "Created by a person",
  ai_assisted: "Created with AI assistance",
  ai_generated: "Generated by AI",
};

export const HUMAN_EDIT_LABELS: Record<(typeof HUMAN_EDITS)[number], string> = {
  none: "No human edits",
  minor: "Minor human edits",
  substantial: "Substantial human edits",
};

export const REGION_LABELS: Record<
  (typeof DISTRIBUTION_REGIONS)[number],
  string
> = {
  us: "United States",
  eu: "European Union",
  uk: "United Kingdom",
  other: "Other regions",
  unspecified: "Unspecified",
};

export const CATEGORY_LABELS: Record<
  (typeof CONTENT_CATEGORIES)[number],
  string
> = {
  product_documentation: "Product documentation",
  marketing: "Marketing",
  editorial: "Editorial",
  training: "Training",
  other: "Other",
};

export const DEPICTION_LABELS: Record<
  (typeof REALISTIC_DEPICTIONS)[number],
  string
> = {
  not_realistic: "Not a realistic depiction",
  stylized: "Stylized",
  photorealistic: "Photorealistic",
  unknown: "Unknown",
};

export const PUBLIC_INTEREST_LABELS: Record<
  (typeof PUBLIC_INTEREST_STATUSES)[number],
  string
> = {
  none: "No public-interest information",
  contains_public_interest: "Contains public-interest information",
  unknown: "Unknown",
};

export const EDITORIAL_REVIEW_LABELS: Record<
  (typeof EDITORIAL_REVIEW_STATUSES)[number],
  string
> = {
  not_reviewed: "Not editorially reviewed",
  internally_reviewed: "Internally reviewed",
  externally_reviewed: "Externally reviewed",
};

export const VERSION_STATUS_LABELS = {
  draft: "Draft declaration",
  pending_review: "Pending human review",
  reviewed: "Reviewed declaration",
} as const;

export const ASSESSMENT_STATUS_LABELS = {
  current: "Current recommendation",
  superseded: "Superseded recommendation",
  invalidated: "Invalidated recommendation",
} as const;
